### ISSUE TITLE
can not use sql_query bind paramters

### ISSUE THREAD

**Issue by stevenkitter** [GiGainfosystems/diesel-oci#53] opened 2024-01-31 08:08 UTC
value: QueryBuilderError("Invalid bind with name: in0")

**Comment by weiznich** [comment] 2024-01-31 08:26
Thanks for filling this bug report.
Can you provide a complete reproducible example including information about your operating system and your oracle (client) library versions?

**Comment by weiznich** [comment] 2024-02-02 07:15
I've tried to locally reproduce this with the following code:

```rust
#[derive(QueryableByName, Debug)]
struct User {
    #[diesel(sql_type = Integer)]
    #[diesel(column_name = "ID")]
    id: i32,
}

fn main() {
    let mut conn = OciConnection::establish("oracle://gst:gst@172.17.0.2/XEPDB1").unwrap();

    let query = diesel::sql_query("select :in0 as id from dual").bind::<Integer, _>(1).load::<User>(&mut conn);
    dbg!(query);
}
```

This runs the query and returns a single item as expected, which means I cannot reproduce your error there. 
That's with:

* diesel 2.1.4
* diesel_oci 0.2.1
* rustc 1.75
* Oracle Database 21c Express Edition Release 21.0.0.0.0

I will close this issue as cannot reproduce. Feel free to add a minimal reproducing example if that continues to happen for you, so that we can investigate it.

**Closed by weiznich** 2024-02-02 07:15 UTC
